### PR TITLE
Contribute Applications of stacks 

### PR DESCRIPTION
**Pull request by garudahalli000**
Hi guys as you know, stacks is an abstract data type which is used for various purpose , i have added some applications of stacks and also the basic operations of stacks.
Hope this helps you guys , thank you!

### CODE REVIEW

**Comment by garudahalli000** [comment]
Bro plz merge it quickly bro as i am late for the fest , 🙏Plz add the hacktoberfest-accepted lable so as to not get excluded

**Review by sourav2002 — CHANGES_REQUESTED** [review]
hi, can you please put all these files in a subfolder as c language?
Stack / c_language/ yourFileName.c

**Review by sourav2002 — APPROVED** [review]

**Comment by garudahalli000** [comment]
Bro do you want to me to do do the sub folder part , because I uploaded my files under stack subfolder only , so you want me to create another subfolder C programme and add these files there?

**Comment by sourav2002** [comment]
No need. I will do it by myself.

**Pull request merged**
