### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by GeekyPS**

### CODE REVIEW

**Comment by sourav2002** [comment]
I am merging your pull request. But there is a chance that this pull request will not be considered. Because I get to know that this time DSA related repos are not allowed for hacktoberfest. You will get to know if your this contribution is counted or not after 7 days.

**Comment by minhaj-313** [comment]
I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best

**Comment by sourav2002** [comment]
> I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best

@minhaj-313  thanks buddy😊 I will message you by tomorrow. I am creating another project for hacktoberfest.

**Comment by minhaj-313** [comment]
@sourav2002  Ok bro I am Waiting

**Pull request merged**
